In [ ]:
import pandas as pd

df = pd.read_csv("data.csv")

df.head()

,0,tcp,private,REJ,0.1,0.2,0.3,0.4,0.5,0.6,...,0.04.1,0.06.1,0.00.3,0.00.4,0.00.5,0.00.6,1.00.2,1.00.3,neptune,21
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.00,0.0,1.00,1.00,neptune,21
1,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.00,0.0,0.00,0.00,normal,21
2,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.00,0.0,0.00,0.00,saint,15
3,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.00,0.0,0.83,0.71,mscan,11
4,0,tcp,http,SF,267,14515,0,0,0,0,...,1.00,0.00,0.01,0.03,0.01,0.0,0.00,0.00,normal,21

In [3]:
df.columns

Index(['0', 'tcp', 'private', 'REJ', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6',
       '0.7', '0.8', '0.9', '0.10', '0.11', '0.12', '0.13', '0.14', '0.15',
       '0.16', '0.17', '0.18', '229', '10', '0.00', '0.00.1', '1.00', '1.00.1',
       '0.04', '0.06', '0.00.2', '255', '10.1', '0.04.1', '0.06.1', '0.00.3',
       '0.00.4', '0.00.5', '0.00.6', '1.00.2', '1.00.3', 'neptune', '21'],
      dtype='str')

In [4]:
import pandas as pd

df = pd.read_csv("data.csv", header=None)

df.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0,tcp,private,REJ,0,0,0,0,0,0,...,0.04,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
1,0,tcp,private,REJ,0,0,0,0,0,0,...,0.00,0.06,0.00,0.00,0.0,0.0,1.00,1.00,neptune,21
2,2,tcp,ftp_data,SF,12983,0,0,0,0,0,...,0.61,0.04,0.61,0.02,0.0,0.0,0.00,0.00,normal,21
3,0,icmp,eco_i,SF,20,0,0,0,0,0,...,1.00,0.00,1.00,0.28,0.0,0.0,0.00,0.00,saint,15
4,1,tcp,telnet,RSTO,0,15,0,0,0,0,...,0.31,0.17,0.03,0.02,0.0,0.0,0.83,0.71,mscan,11

In [5]:
df.shape

(22544, 43)

In [6]:
X = df.iloc[:, :-1]   # all columns except last
y = df.iloc[:, -1]    # last column

print(X.head())
print(y.head())

   0     1         2     3      4   5   6   7   8   9   ...  32    33    34  \
0   0   tcp   private   REJ      0   0   0   0   0   0  ...  10  0.04  0.06
1   0   tcp   private   REJ      0   0   0   0   0   0  ...   1  0.00  0.06
2   2   tcp  ftp_data    SF  12983   0   0   0   0   0  ...  86  0.61  0.04
3   0  icmp     eco_i    SF     20   0   0   0   0   0  ...  57  1.00  0.00
4   1   tcp    telnet  RSTO      0  15   0   0   0   0  ...  86  0.31  0.17

     35    36   37   38    39    40       41
0  0.00  0.00  0.0  0.0  1.00  1.00  neptune
1  0.00  0.00  0.0  0.0  1.00  1.00  neptune
2  0.61  0.02  0.0  0.0  0.00  0.00   normal
3  1.00  0.28  0.0  0.0  0.00  0.00    saint
4  0.03  0.02  0.0  0.0  0.83  0.71    mscan

[5 rows x 42 columns]
0    21
1    21
2    21
3    15
4    11
Name: 42, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# train model
model = RandomForestClassifier()
model.fit(X_train, y_train)

# predict
y_pred = model.predict(X_test)

# accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))

ValueError: could not convert string to float: 'tcp'

In [14]:
from sklearn.preprocessing import LabelEncoder

# convert all columns to numbers
for col in df.columns:
    if df[col].dtype == object:
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col])

In [15]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [17]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

ValueError: could not convert string to float: 'tcp'

In [18]:
# Convert everything to numeric (forcefully)
df = df.apply(pd.to_numeric, errors='coerce')

In [19]:
df = df.fillna(0)

In [20]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [21]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8134841428254602

In [22]:
import joblib

joblib.dump(model, "cybersecurity_model.pkl")

['cybersecurity_model.pkl']

In [23]:
# take one sample
sample = X_test.iloc[0:1]

prediction = model.predict(sample)

print("Prediction:", prediction)
print("Actual:", y_test.iloc[0])

Prediction: [18]
Actual: 18

In [24]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [25]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [26]:
df.iloc[0].to_dict()

{0: 0.0,
 1: 0.0,
 2: 0.0,
 3: 0.0,
 4: 0.0,
 5: 0.0,
 6: 0.0,
 7: 0.0,
 8: 0.0,
 9: 0.0,
 10: 0.0,
 11: 0.0,
 12: 0.0,
 13: 0.0,
 14: 0.0,
 15: 0.0,
 16: 0.0,
 17: 0.0,
 18: 0.0,
 19: 0.0,
 20: 0.0,
 21: 0.0,
 22: 229.0,
 23: 10.0,
 24: 0.0,
 25: 0.0,
 26: 1.0,
 27: 1.0,
 28: 0.04,
 29: 0.06,
 30: 0.0,
 31: 255.0,
 32: 10.0,
 33: 0.04,
 34: 0.06,
 35: 0.0,
 36: 0.0,
 37: 0.0,
 38: 0.0,
 39: 1.0,
 40: 1.0,
 41: 0.0,
 42: 21.0}